apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-postgresql
  labels:
    app: {{ include "myapp.fullname" . }}-postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: {{ include "myapp.fullname" . }}-postgresql