apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-postgresql
spec:
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}-postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}