replicaCount: 2

image:
  repository: satya03521/node-postgres-app
  pullPolicy: Always
  tag: latest

service:
  type: LoadBalancer
  port: 80

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: mydb
  service:
    port: 5432

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1